spring:
  application:
    name: tanhua-dubbo-service
  data:
    mongodb:
      uri: mongodb://159.75.211.245:27017/tanhua

dubbo:
  scan:
    base-packages: org.coderpwh.server
  application:
    name: dubbo-provider-tanhua
  protocol:
    name: dubbo
    port: 20880
    host: 169.254.194.196
  registry:
    address: zookeeper://159.75.211.245:2181
    client: zkclient
logging:
  level:
    org.coderpwh: debug
